ci: add spec06 rvv ci
ci: uncheck the rvv ci result

ci: try vector ci without difftest

diff --git a/.github/workflows/gem5-perf-template.yml b/.github/workflows/gem5-perf-template.yml
--- a/.github/workflows/gem5-perf-template.yml
+++ b/.github/workflows/gem5-perf-template.yml
@@ -9,8 +9,16 @@ on:
       benchmark_type:
         required: true
         type: string
-        description: "Benchmark type: spec06-0.8c, spec06-1.0c, or spec17-1.0c"
-
+        description: "Benchmark type: spec06-0.8c, spec06-1.0c, spec17-1.0c, spec06-rvv-1.0c or spec06-rvv-1.0c-fix"
+      vector_type:
+        required: false
+        type: string
+        description: "Benchmark type: base, simple"
+      check_result:
+        required: false
+        type: boolean
+        description: "Whether to check result (failed ckpts)"
+        default: true
 jobs:
   run_performance_test:
     runs-on: [self-hosted, node]
@@ -46,8 +54,24 @@ jobs:
               echo "artifact_name=performance-score-spec17-1.0c" >> $GITHUB_OUTPUT
               echo "comment=run 100% coverage spec17 checkpoints" >> $GITHUB_OUTPUT
               ;;
+            "spec06-rvv-1.0c")
+              echo "checkpoint_list=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/checkpoint.lst" >> $GITHUB_OUTPUT
+              echo "checkpoint_root_node=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/" >> $GITHUB_OUTPUT
+              echo "score_script=gem5-score-ci.sh" >> $GITHUB_OUTPUT
+              echo "cluster_config=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/cluster-0-0.json" >> $GITHUB_OUTPUT
+              echo "artifact_name=performance-score-spec06-1.0c-with-rvv-extension" >> $GITHUB_OUTPUT
+              echo "comment=run 100% coverage spec06 rvv checkpoints" >> $GITHUB_OUTPUT
+              ;;
+            "spec06-rvv-1.0c-fix")
+              echo "checkpoint_list=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/checkpoint-fixed.lst" >> $GITHUB_OUTPUT
+              echo "checkpoint_root_node=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/" >> $GITHUB_OUTPUT
+              echo "score_script=gem5-score-ci.sh" >> $GITHUB_OUTPUT
+              echo "cluster_config=/nfs/home/xutongqiao/GEM5-CI/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint06_rv64gcbv/cluster-0-0.json" >> $GITHUB_OUTPUT
+              echo "artifact_name=performance-score-spec06-1.0c-with-rvv-extension" >> $GITHUB_OUTPUT
+              echo "comment=run 100% (fixed) coverage spec06 rvv checkpoints" >> $GITHUB_OUTPUT
+              ;;
             *)
-              echo "Error: Invalid benchmark_type '${{ inputs.benchmark_type }}'. Must be one of: spec06-0.8c, spec06-1.0c, spec17-1.0c"
+              echo "Error: Invalid benchmark_type '${{ inputs.benchmark_type }}'. Must be one of: spec06-0.8c, spec06-1.0c, spec17-1.0c, spec06-rvv-1.0c or spec06-rvv-1.0c-fix"
               exit 1
               ;;
           esac
@@ -63,15 +87,49 @@ jobs:
           cd $GEM5_HOME
       - name: Build GEM5 fast
         run: |
-          # use pgo profile to build gem5
-          export GEM5_HOME=$(pwd)
-          export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
-          bash util/pgo/basic_pgo_new.sh
+          case "${{ inputs.vector_type }}" in
+            "base")
+              # use pgo profile to build gem5
+              export GEM5_HOME=$(pwd)
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
+              bash util/pgo/basic_pgo_new.sh
+              ;;
+            "simple")
+              # use pgo profile to build gem5
+              export GEM5_HOME=$(pwd)
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-notama-so"
+              bash util/pgo/basic_pgo_new_vector.sh
+              ;;
+            "")
+              # unset vector_type, use "base"
+              export GEM5_HOME=$(pwd)
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
+              bash util/pgo/basic_pgo_new.sh
+              ;;
+            *)
+              echo "Error: Invalid vector_type '${{ inputs.vector_type }}'. Must be one of: base, simple"
+              exit 1
+              ;;
+          esac
+
       - name: XS-GEM5 - Run performance test
         # ${{ steps.config.outputs.comment }}
         run: |
-
-          export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
+          case "${{ inputs.vector_type }}" in
+            "base")
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
+              ;;
+            "simple")
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-notama-so"
+              ;;
+            "")
+              export GCBV_REF_SO="/nfs/home/share/gem5_ci/ref/normal/riscv64-nemu-interpreter-so"
+              ;;
+            *)
+              echo "Error: Invalid vector_type '${{ inputs.vector_type }}'. Must be one of: base, simple"
+              exit 1
+              ;;
+          esac
           export GCB_RESTORER=""
           export GEM5_HOME=$(pwd)
           export GEM5_BUILD_TYPE=fast
@@ -119,7 +177,9 @@ jobs:
               while read -r line; do
                 echo "- $line" >> $GITHUB_STEP_SUMMARY
               done
-            exit 1
+              if [ "${{ inputs.check_result }}" == "true" ]; then
+                exit 1
+              fi
           fi
       - name: Archive performance data
         if: always()
